name: Build and push container

on:
  push:
    branches: [main]

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Get short commit sha
        id: vars
        shell: bash
        run: |
          echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to private docker registery
        uses: docker/login-action@v2
        with:
          registry: registery.unknownclouds.com
          username: ${{ secrets.DOCKER_REGISTERY_USERNAME }}
          password: ${{ secrets.DOCKER_REGISTERY_PASSWORD }}
      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: registery.unknownclouds.com/rtcv:${{ steps.vars.outputs.sha_short }}
          outputs: type=docker,dest=/tmp/docker-image.tar
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: docker-image
          path: /tmp/docker-image.tar
